theme: jekyll-theme-minimal
title: Design Patterns - Work for COMM 363
description: This site will be used for the implementation of design pattern work and other projects from a college class on web design.
